import type {
  Case,
  CaseMessage,
  Client,
  Escalation,
  Hotel,
  Invoice,
  Approval,
} from "@/types";

const now = Date.now();
const mins = (n: number) => new Date(now - n * 60_000).toISOString();
const hrs = (n: number) => new Date(now - n * 3_600_000).toISOString();
const days = (n: number) => new Date(now - n * 86_400_000).toISOString();

export const cases: Case[] = [
  {
    id: "case_1",
    code: "CASE-2026-05-3987",
    type: "URGENT_CHECKIN_ISSUE",
    status: "ESCALATED_TO_HUMAN",
    priority: "P0",
    riskScore: 95,
    ownerName: "Sarah Lee",
    clientName: "Linh Tran Travel",
    hotelName: "ABC Hotel Da Nang",
    bookingCode: "BKG-2026-09-1234",
    subject: "URGENT: 손님 지금 호텔 로비인데 예약 없대요",
    preview:
      "우리 손님이 다낭 ABC호텔에 도착했는데 호텔이 예약 없다고 합니다. 지금 5/10 13:00...",
    language: "ko",
    slaRemainingSec: 240,
    slaTotalSec: 1800,
    createdAt: mins(28),
    updatedAt: mins(2),
    unread: true,
  },
  {
    id: "case_2",
    code: "CASE-2026-05-3986",
    type: "OVERBOOKING",
    status: "WAITING_FOR_HOTEL",
    priority: "P1",
    riskScore: 72,
    ownerName: "Min-jung Kim",
    clientName: "Tokyo Holidays Inc",
    hotelName: "Sakura Inn Kyoto",
    bookingCode: "BKG-2026-09-1198",
    subject: "Sorry, overbooked for the night of May 14",
    preview:
      "We regret to inform you that due to an unexpected situation, we are unable to honor...",
    language: "en",
    slaRemainingSec: -1800,
    slaTotalSec: 14400,
    createdAt: hrs(6),
    updatedAt: mins(45),
  },
  {
    id: "case_3",
    code: "CASE-2026-05-3985",
    type: "BOOKING_CONFIRMATION",
    status: "WAITING_FOR_HOTEL",
    priority: "P2",
    riskScore: 38,
    ownerName: "Sarah Lee",
    clientName: "VietGo Tours",
    hotelName: "Hanoi Pearl Hotel",
    bookingCode: "BKG-2026-09-1187",
    subject: "Confirmation request for Hong Gildong group (3 rooms, May 18-20)",
    preview:
      "Dear Reservations Team, We would like to confirm the following booking for our group...",
    language: "en",
    slaRemainingSec: 4200,
    slaTotalSec: 14400,
    createdAt: hrs(3),
    updatedAt: hrs(2),
  },
  {
    id: "case_4",
    code: "CASE-2026-05-3984",
    type: "PAYMENT_OVERDUE",
    status: "OVERDUE_D3",
    priority: "P1",
    riskScore: 64,
    ownerName: "Lee Soyoung",
    clientName: "Bali Sunrise DMC",
    bookingCode: "INV-2026-04-998",
    subject: "INV-2026-04-998 결제 D+3 경과",
    preview: "USD 4,800 인보이스 만기가 5/1이었으며 현재 D+3 경과...",
    language: "ko",
    slaRemainingSec: -3600,
    slaTotalSec: 86400,
    createdAt: days(4),
    updatedAt: hrs(20),
  },
  {
    id: "case_5",
    code: "CASE-2026-05-3983",
    type: "ROOM_TYPE_MISMATCH",
    status: "DATA_MATCH_NEEDED",
    priority: "P2",
    riskScore: 41,
    ownerName: "Hong Junho",
    clientName: "Seoul Premier Tours",
    hotelName: "Bangkok Grand Palace",
    bookingCode: "BKG-2026-09-1156",
    subject: "Re: Confirmation BKG-2026-09-1156 — Room type query",
    preview:
      "Confirmed Standard Room x2 instead of Deluxe Twin x2 — please advise on rate adjustment...",
    language: "en",
    slaRemainingSec: 9600,
    slaTotalSec: 14400,
    createdAt: hrs(8),
    updatedAt: hrs(5),
  },
  {
    id: "case_6",
    code: "CASE-2026-05-3982",
    type: "CREDIT_LIMIT_WARNING",
    status: "CREDIT_LIMIT_WARNING",
    priority: "P2",
    riskScore: 52,
    ownerName: "Park Jin",
    clientName: "Phuket Beach Resort Co",
    subject: "신용 한도 92% 도달 — 신규 부킹 검토 필요",
    preview:
      "현재 utilization 92% (한도 $50,000 / 노출 $46,200). 신규 부킹 $4,200 진행 시...",
    language: "ko",
    slaRemainingSec: 64800,
    slaTotalSec: 86400,
    createdAt: hrs(12),
    updatedAt: hrs(2),
  },
  {
    id: "case_7",
    code: "CASE-2026-05-3981",
    type: "CLIENT_INQUIRY",
    status: "WAITING_FOR_HUMAN_APPROVAL",
    priority: "P3",
    riskScore: 18,
    ownerName: "Min-jung Kim",
    clientName: "Hanoi Travel Group",
    bookingCode: "BKG-2026-09-1092",
    subject: "예약 BKG-2026-09-1092 진행 상태 문의",
    preview: "안녕하세요, 5/15 체크인 예약 상태가 어떻게 되나요?",
    language: "ko",
    slaRemainingSec: 7200,
    slaTotalSec: 14400,
    createdAt: hrs(2),
    updatedAt: mins(15),
  },
  {
    id: "case_8",
    code: "CASE-2026-05-3980",
    type: "REFUND",
    status: "FINANCE_REVIEWING",
    priority: "P1",
    riskScore: 58,
    ownerName: "Lee Soyoung",
    clientName: "Osaka Travel Co",
    bookingCode: "BKG-2026-08-0987",
    subject: "환불 요청 — 호텔 측 사유 (시설 공사)",
    preview:
      "호텔이 5/3-5/5 시설 공사로 객실 사용 불가 통보. 클라이언트 환불 요청 + 호텔 클레임 필요...",
    language: "ko",
    slaRemainingSec: 86400,
    slaTotalSec: 172800,
    createdAt: days(2),
    updatedAt: hrs(8),
  },
  {
    id: "case_9",
    code: "CASE-2026-05-3979",
    type: "NO_SHOW_DISPUTE",
    status: "WAITING_FOR_CLIENT",
    priority: "P2",
    riskScore: 47,
    ownerName: "Hong Junho",
    clientName: "Saigon Express Travel",
    hotelName: "Phu Quoc Pearl Resort",
    bookingCode: "BKG-2026-08-0921",
    subject: "Hotel claims no-show — client disputes",
    preview:
      "Hotel charging 100% no-show fee USD 380. Client says guest checked in. Awaiting evidence...",
    language: "en",
    slaRemainingSec: 21600,
    slaTotalSec: 259200,
    createdAt: days(3),
    updatedAt: hrs(28),
  },
  {
    id: "case_10",
    code: "CASE-2026-05-3978",
    type: "BOOKING_CONFIRMATION",
    status: "RESOLVED",
    priority: "P3",
    riskScore: 12,
    ownerName: "Sarah Lee",
    clientName: "Bangkok Voyage Co",
    hotelName: "Chiang Mai Heritage",
    bookingCode: "BKG-2026-09-1145",
    subject: "Booking confirmed — Anderson family / May 20-22",
    preview: "Hotel confirmed. Confirmation #HCN-TH-7724.",
    language: "en",
    slaRemainingSec: 0,
    slaTotalSec: 14400,
    createdAt: days(1),
    updatedAt: hrs(4),
  },
];

export const hotels: Hotel[] = [
  {
    id: "h_1",
    code: "HTL-DA-NANG-007",
    name: "ABC Hotel Da Nang",
    country: "VN",
    language: "vi",
    responseRate30d: 0.78,
    avgResponseSec: 64800,
    slaResponseSec: 86400,
    autoSendAllowed: true,
    contactsCount: 2,
    lastContactedAt: mins(36),
  },
  {
    id: "h_2",
    code: "HTL-KYOTO-002",
    name: "Sakura Inn Kyoto",
    country: "JP",
    language: "ja",
    responseRate30d: 0.92,
    avgResponseSec: 14400,
    slaResponseSec: 21600,
    autoSendAllowed: true,
    contactsCount: 3,
    lastContactedAt: hrs(2),
  },
  {
    id: "h_3",
    code: "HTL-HANOI-014",
    name: "Hanoi Pearl Hotel",
    country: "VN",
    language: "vi",
    responseRate30d: 0.85,
    avgResponseSec: 32400,
    slaResponseSec: 43200,
    autoSendAllowed: true,
    contactsCount: 2,
    lastContactedAt: hrs(3),
  },
  {
    id: "h_4",
    code: "HTL-BKK-009",
    name: "Bangkok Grand Palace",
    country: "TH",
    language: "en",
    responseRate30d: 0.91,
    avgResponseSec: 18000,
    slaResponseSec: 21600,
    autoSendAllowed: true,
    contactsCount: 3,
    lastContactedAt: hrs(8),
  },
  {
    id: "h_5",
    code: "HTL-PHUKET-003",
    name: "Phuket Beach Resort",
    country: "TH",
    language: "en",
    responseRate30d: 0.68,
    avgResponseSec: 86400,
    slaResponseSec: 43200,
    autoSendAllowed: false,
    contactsCount: 1,
    lastContactedAt: days(2),
  },
  {
    id: "h_6",
    code: "HTL-CMI-018",
    name: "Chiang Mai Heritage",
    country: "TH",
    language: "en",
    responseRate30d: 0.95,
    avgResponseSec: 7200,
    slaResponseSec: 14400,
    autoSendAllowed: true,
    contactsCount: 2,
    lastContactedAt: hrs(4),
  },
  {
    id: "h_7",
    code: "HTL-OSAKA-006",
    name: "Osaka Riverside Hotel",
    country: "JP",
    language: "ja",
    responseRate30d: 0.88,
    avgResponseSec: 21600,
    slaResponseSec: 28800,
    autoSendAllowed: true,
    contactsCount: 2,
    lastContactedAt: hrs(6),
  },
  {
    id: "h_8",
    code: "HTL-PQ-022",
    name: "Phu Quoc Pearl Resort",
    country: "VN",
    language: "vi",
    responseRate30d: 0.71,
    avgResponseSec: 50400,
    slaResponseSec: 43200,
    autoSendAllowed: false,
    contactsCount: 1,
    lastContactedAt: days(1),
  },
];

export const clients: Client[] = [
  {
    id: "c_1",
    code: "CLT-VN-LINH-007",
    name: "Linh Tran Travel",
    country: "VN",
    tier: "VIP",
    language: "ko",
    accountManager: "Kim AM",
    creditLimit: 50000,
    outstanding: 12000,
    pipeline: 18000,
    utilizationPct: 0.6,
    avgDso: 42,
    bookings30d: 45,
    cases30d: 12,
    currency: "USD",
  },
  {
    id: "c_2",
    code: "CLT-JP-TKY-002",
    name: "Tokyo Holidays Inc",
    country: "JP",
    tier: "Premium",
    language: "ja",
    accountManager: "Park Sales",
    creditLimit: 80000,
    outstanding: 24500,
    pipeline: 31200,
    utilizationPct: 0.696,
    avgDso: 38,
    bookings30d: 78,
    cases30d: 18,
    currency: "USD",
  },
  {
    id: "c_3",
    code: "CLT-VN-VG-014",
    name: "VietGo Tours",
    country: "VN",
    tier: "Standard",
    language: "vi",
    accountManager: "Kim AM",
    creditLimit: 30000,
    outstanding: 4200,
    pipeline: 8800,
    utilizationPct: 0.433,
    avgDso: 35,
    bookings30d: 32,
    cases30d: 7,
    currency: "USD",
  },
  {
    id: "c_4",
    code: "CLT-ID-BS-009",
    name: "Bali Sunrise DMC",
    country: "ID",
    tier: "Premium",
    language: "en",
    accountManager: "Park Sales",
    creditLimit: 60000,
    outstanding: 38400,
    pipeline: 14200,
    utilizationPct: 0.877,
    avgDso: 71,
    bookings30d: 28,
    cases30d: 14,
    currency: "USD",
  },
  {
    id: "c_5",
    code: "CLT-KR-SP-005",
    name: "Seoul Premier Tours",
    country: "KR",
    tier: "VIP",
    language: "ko",
    accountManager: "Kim AM",
    creditLimit: 120000,
    outstanding: 18200,
    pipeline: 42000,
    utilizationPct: 0.502,
    avgDso: 28,
    bookings30d: 96,
    cases30d: 22,
    currency: "USD",
  },
  {
    id: "c_6",
    code: "CLT-TH-PB-011",
    name: "Phuket Beach Resort Co",
    country: "TH",
    tier: "Standard",
    language: "en",
    accountManager: "Park Sales",
    creditLimit: 50000,
    outstanding: 28100,
    pipeline: 18100,
    utilizationPct: 0.924,
    avgDso: 65,
    bookings30d: 18,
    cases30d: 9,
    currency: "USD",
  },
  {
    id: "c_7",
    code: "CLT-VN-HN-018",
    name: "Hanoi Travel Group",
    country: "VN",
    tier: "Standard",
    language: "ko",
    accountManager: "Kim AM",
    creditLimit: 25000,
    outstanding: 6400,
    pipeline: 4200,
    utilizationPct: 0.424,
    avgDso: 41,
    bookings30d: 22,
    cases30d: 5,
    currency: "USD",
  },
  {
    id: "c_8",
    code: "CLT-JP-OS-021",
    name: "Osaka Travel Co",
    country: "JP",
    tier: "Premium",
    language: "ja",
    accountManager: "Park Sales",
    creditLimit: 70000,
    outstanding: 3200,
    pipeline: 22400,
    utilizationPct: 0.366,
    avgDso: 22,
    bookings30d: 41,
    cases30d: 8,
    currency: "USD",
  },
];

export const invoices: Invoice[] = [
  {
    id: "inv_1",
    code: "INV-2026-04-998",
    clientName: "Bali Sunrise DMC",
    amount: 4800,
    paid: 0,
    balance: 4800,
    currency: "USD",
    status: "SENT",
    issueDate: "2026-04-01",
    dueDate: "2026-05-01",
    daysToDue: -3,
    agingBucket: "0-30",
  },
  {
    id: "inv_2",
    code: "INV-2026-04-987",
    clientName: "Bali Sunrise DMC",
    amount: 12400,
    paid: 0,
    balance: 12400,
    currency: "USD",
    status: "SENT",
    issueDate: "2026-03-15",
    dueDate: "2026-04-14",
    daysToDue: -20,
    agingBucket: "0-30",
  },
  {
    id: "inv_3",
    code: "INV-2026-03-921",
    clientName: "Tokyo Holidays Inc",
    amount: 18900,
    paid: 8000,
    balance: 10900,
    currency: "USD",
    status: "PARTIAL",
    issueDate: "2026-03-01",
    dueDate: "2026-04-30",
    daysToDue: -4,
    agingBucket: "0-30",
  },
  {
    id: "inv_4",
    code: "INV-2026-03-901",
    clientName: "Phuket Beach Resort Co",
    amount: 8200,
    paid: 0,
    balance: 8200,
    currency: "USD",
    status: "SENT",
    issueDate: "2026-02-15",
    dueDate: "2026-03-17",
    daysToDue: -48,
    agingBucket: "31-60",
  },
  {
    id: "inv_5",
    code: "INV-2026-02-845",
    clientName: "Phuket Beach Resort Co",
    amount: 19900,
    paid: 0,
    balance: 19900,
    currency: "USD",
    status: "DISPUTED",
    issueDate: "2026-02-01",
    dueDate: "2026-03-03",
    daysToDue: -62,
    agingBucket: "61-90",
  },
  {
    id: "inv_6",
    code: "INV-2026-04-1012",
    clientName: "Linh Tran Travel",
    amount: 12000,
    paid: 0,
    balance: 12000,
    currency: "USD",
    status: "SENT",
    issueDate: "2026-04-15",
    dueDate: "2026-05-15",
    daysToDue: 11,
    agingBucket: null,
  },
  {
    id: "inv_7",
    code: "INV-2026-04-1024",
    clientName: "Seoul Premier Tours",
    amount: 18200,
    paid: 0,
    balance: 18200,
    currency: "USD",
    status: "VIEWED",
    issueDate: "2026-04-20",
    dueDate: "2026-05-20",
    daysToDue: 16,
    agingBucket: null,
  },
];

export const escalations: Escalation[] = [
  {
    id: "esc_1",
    caseCode: "CASE-2026-05-3987",
    reason: "URGENT_CHECKIN",
    riskBand: "CRITICAL",
    level: 2,
    recipientRole: "Account Manager",
    ackDeadlineSec: 240,
    triggeredAt: mins(8),
    summary:
      "VIP Linh / RV-2026-1234 / 다낭 ABC호텔 / 게스트 체크인 실패 (D-0). 호텔 36h 무응답.",
  },
  {
    id: "esc_2",
    caseCode: "CASE-2026-05-3986",
    reason: "OVERBOOKING_DAY_OF",
    riskBand: "HIGH",
    level: 1,
    recipientRole: "Team Leader",
    ackDeadlineSec: 1620,
    triggeredAt: mins(20),
    summary: "Sakura Inn Kyoto overbooked for 5/14 — 대체 호텔 수배 필요. Tokyo Holidays VIP.",
  },
  {
    id: "esc_3",
    caseCode: "CASE-2026-05-3984",
    reason: "AGING_60+",
    riskBand: "HIGH",
    level: 1,
    recipientRole: "Finance Manager",
    ackDeadlineSec: 7200,
    triggeredAt: hrs(1),
    summary: "Bali Sunrise DMC — Aging 31-60 $20,400 중 분쟁 가능성 의심. AM 통화 권장.",
  },
];

export const approvals: Approval[] = [
  {
    id: "apr_1",
    kind: "DRAFT_SEND",
    caseCode: "CASE-2026-05-3987",
    requesterName: "AI Drafting Agent",
    subject: "Hotel ABC Da Nang — 긴급 컨펌 요청 메일 (KO/EN 다국어)",
    riskBand: "CRITICAL",
    deadlineSec: 240,
    aiRecommendation:
      "호텔 직통 통화 또는 대체 호텔 즉시 수배. confidence 0.97 — 게스트 D-0 + 36h 무응답 + VIP",
  },
  {
    id: "apr_2",
    kind: "DRAFT_SEND",
    caseCode: "CASE-2026-05-3981",
    requesterName: "AI Drafting Agent",
    subject: "Hanoi Travel Group — 부킹 상태 회신 드래프트",
    riskBand: "LOW",
    deadlineSec: 7200,
    aiRecommendation: "정형 상태 회신. confidence 0.94 — 자동 발송 가능 후보",
  },
  {
    id: "apr_3",
    kind: "REFUND",
    caseCode: "CASE-2026-05-3980",
    requesterName: "Lee Soyoung",
    subject: "Osaka Travel Co — USD 1,140 환불 (호텔 측 사유)",
    riskBand: "MEDIUM",
    deadlineSec: 172800,
    aiRecommendation: "호텔 클레임 가능성 높음. 환불 후 호텔에 차액 청구 권장.",
  },
  {
    id: "apr_4",
    kind: "LIMIT_INCREASE",
    caseCode: "CASE-2026-05-3982",
    requesterName: "Park Sales",
    subject: "Phuket Beach Resort Co — 한도 $50K → $65K 인상 요청",
    riskBand: "HIGH",
    deadlineSec: 86400,
    aiRecommendation:
      "현재 utilization 92% + Aging 61-90 분쟁. 인상 거절 또는 선결제 50% 권장.",
  },
];

export const caseMessages: Record<string, CaseMessage[]> = {
  case_1: [
    {
      id: "m1",
      caseId: "case_1",
      direction: "INBOUND",
      actor: "Linh Tran (Client)",
      actorKind: "CLIENT",
      subject: "URGENT: 손님 지금 호텔 로비인데 예약 없대요 RV-2026-1234",
      body:
        "안녕하세요, 우리 손님이 다낭 ABC호텔에 도착했는데 호텔이 예약 없다고 합니다. 지금 5/10 13:00 입니다. 빠른 회신 부탁드립니다.",
      language: "ko",
      at: mins(28),
    },
    {
      id: "m2",
      caseId: "case_1",
      direction: "AI_ACTION",
      actor: "Email Intake Agent",
      actorKind: "AI",
      body:
        "Classified: URGENT_CHECKIN_ISSUE. Risk: CRITICAL (95). Hard trigger: URGENT_CHECKIN. → SOP_URGENT_CHECKIN triggered.",
      at: mins(28),
      confidence: 0.96,
    },
    {
      id: "m3",
      caseId: "case_1",
      direction: "STATUS_CHANGE",
      actor: "System",
      actorKind: "SYSTEM",
      body: "NEW → AI_REVIEWING → ESCALATED_TO_HUMAN",
      at: mins(28),
    },
    {
      id: "m4",
      caseId: "case_1",
      direction: "ESCALATION",
      actor: "Escalation Engine",
      actorKind: "SYSTEM",
      body:
        "Level 1 → Team Leader (Slack + Email). Level 2 → Account Manager + COO SMS. Ack deadline 30분.",
      at: mins(27),
    },
    {
      id: "m5",
      caseId: "case_1",
      direction: "OUTBOUND",
      actor: "AI Drafting Agent",
      actorKind: "AI",
      subject: "[URGENT] Confirmation BKG-2026-09-1234 — Guest at lobby now",
      body:
        "Dear ABC Hotel Reservations Team,\n\nWe have a guest currently at your lobby (CI 2026-05-10) being told there is no reservation. Please find original confirmation HCN-VN-9911 attached.\n\nGuest: Hong Gildong\nBooking: BKG-2026-09-1234\nCheck-in: 2026-05-10 (TODAY)\nCheck-out: 2026-05-12\nRoom: 1x Deluxe Twin\n\nPlease confirm immediately. We will call your direct line in 5 minutes.\n\nBest regards,\nSarah Lee\nReservations Team",
      language: "en",
      at: mins(26),
      pendingApproval: true,
      confidence: 0.93,
    },
    {
      id: "m6",
      caseId: "case_1",
      direction: "INTERNAL_NOTE",
      actor: "Sarah Lee",
      actorKind: "USER",
      body: "@team-leader 호텔 직통 +84-236-... 통화 시작합니다. 대체 호텔 후보 풀 준비.",
      at: mins(20),
    },
    {
      id: "m7",
      caseId: "case_1",
      direction: "AI_ACTION",
      actor: "Risk Detection Agent",
      actorKind: "AI",
      body:
        "대체 호텔 후보 3개 추천 — Furama Da Nang ($210/night, 동급), Vinpearl Da Nang ($245), Sheraton ($310). 모두 직거래.",
      at: mins(15),
      confidence: 0.89,
    },
  ],
};
